### ISSUE TITLE
Is it possible to change MOUNT_DIR value?

### ISSUE THREAD

**Issue by PraveenJP** [ashald/docker-volume-loopback#1]
```
docker plugin set ashald/docker-volume-loopback MOUNT_DIR="/net/server/fs0/home/user/docker_volumes"
Error response from daemon: "MOUNT_DIR" is not settable
```

**Comment by ashald** [comment]
It's indeed not - as documented in https://github.com/ashald/docker-volume-loopback#configuration
Docker doesn't allow it.
If you need to change it, you can do so via env vars or CLI arguments, but for that you'd need to use a manual installation mode https://github.com/ashald/docker-volume-loopback#manual

**Comment by PraveenJP** [comment]
But any permission required for /mnt because after I created volume nothing happened inside the /mnt folder because my expectation like it should create one folder based on volume name..
